# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    build: host
    user: root
    privileged: true
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    environment:
      CASC_JENKINS_CONFIG: /my_marvin.yml
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      BUILDER_PASSWORD_FILE: /run/secrets/builder_password
      GITHUB_TOKEN_FILE: /run/secrets/github_token
      GITHUB_SSH_KEY_FILE: /run/secrets/github_ssh_key
    secrets:
      - admin_password
      - builder_password
      - github_token
      - github_ssh_key

secrets:
  admin_password:
    file: secrets/admin_password
  builder_password:
    file: secrets/builder_password
  github_token:
    file: secrets/github_token
  github_ssh_key:
    file: secrets/github_ssh_key

volumes:
  jenkins-data:
