- name: "Download helm install script"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: 0755
  changed_when: false

- name: "Install helm"
  ansible.builtin.command: /tmp/get_helm.sh
  changed_when: false

- name: "Check if namespace 'jenkins' already exists"
  ansible.builtin.command: kubectl get namespace jenkins
  ignore_errors: yes
  changed_when: false
  register: namespace_check
  failed_when: "'NotFound' in namespace_check.stderr"

- name: "Create namespace 'jenkins'"
  ansible.builtin.command: kubectl create namespace jenkins
  when: namespace_check is failed
  changed_when: false

- name: "Check if service account already exists"
  ansible.builtin.command: kubectl get serviceaccount jenkins-agent --namespace jenkins
  ignore_errors: yes
  changed_when: false
  failed_when: "'NotFound' in service_account_check.stderr"
  register: service_account_check

- name: "Create service account"
  ansible.builtin.command: kubectl create serviceaccount jenkins-agent --namespace jenkins
  changed_when: false
  when: service_account_check is failed

- name: "Check if cluster role binding already exists"
  ansible.builtin.command: kubectl get clusterrolebinding jenkins-agent
  ignore_errors: yes
  changed_when: false
  register: cluster_role_binding_check
  failed_when: "'NotFound' in cluster_role_binding_check.stderr"

- name: "Create cluster role binding"
  ansible.builtin.command: kubectl create clusterrolebinding jenkins-agent --clusterrole cluster-admin --serviceaccount jenkins:jenkins-agent
  changed_when: false
  when: service_account_check is failed

- name: "Create secret token"
  ansible.builtin.command: kubectl create token jenkins-agent --namespace jenkins
  changed_when: false
  register: k8s_create_token

- name: Set a token fact
  set_fact:
    create_k8s_token: "{{ k8s_create_token.stdout }}"
