# Base image
FROM node:20.9.0-bullseye

SHELL ["/bin/bash", "-c"]

WORKDIR /app

# This section will be executed only if the image is used as a base image
ONBUILD COPY . /app
ONBUILD RUN npm install
ONBUILD CMD ["node", "."]
